<?php
/**
 * Created by PhpStorm.
 * User: adrian
 * Date: 19/03/19
 * Time: 13:43
 */
session_start();
$pageTitle = 'Mentions légales';
require '/home/adrian/Documents/dev/billet-simple/src/View/Layout/layout.php'; ?>

    <div class="header-img"></div>
    <h2 class="header-title">Mentions légales</h2>
    <h3 id="title-notice">Mentions légales</h3>
    <p id="legal-notice">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam volutpat metus magna, at porta nulla scelerisque eget. Vivamus a nisi dolor. Vestibulum ut tellus vitae leo ultrices eleifend ac sit amet orci. Donec condimentum ipsum ut lacinia consequat. Proin quis fringilla ante. Pellentesque id condimentum felis, nec venenatis lectus. Sed aliquet id tellus at rutrum. Phasellus placerat nisi dolor, at laoreet diam vehicula a. Duis libero nunc, semper at metus nec, condimentum efficitur ex. Ut lobortis sagittis tellus ac aliquam. Cras convallis, ligula vel vehicula ullamcorper, orci odio auctor ex, eu accumsan mauris arcu et enim. Etiam placerat diam imperdiet tristique porta. Phasellus porta interdum purus, at maximus erat egestas nec. Nunc tincidunt porttitor mi, sit amet feugiat ligula pretium eget.
        </br></br>
        Pellentesque nec sollicitudin ex, ut fermentum leo. Integer condimentum ac ante nec rutrum. Aenean pulvinar hendrerit enim, porttitor lobortis risus volutpat vitae. Etiam at mi ut nisi pulvinar porta sed interdum velit. Ut lacinia in quam quis mattis. Vestibulum ac arcu hendrerit, porttitor odio quis, tempor nisi. Nam id libero purus. Fusce eu mi eget eros tempor placerat malesuada eu purus. Donec non eros sit amet leo dictum consequat eget vel dui. Donec ac cursus turpis, ut condimentum diam. Vivamus luctus urna purus, ut ultricies ipsum tincidunt ac. Suspendisse sit amet ipsum lorem.
        </br></br>
        Nullam urna lorem, pulvinar at urna eu, luctus laoreet felis. Integer neque nunc, congue vitae sapien et, volutpat condimentum nisi. Phasellus ac augue vitae nisi vestibulum gravida eget molestie lacus. Vivamus magna elit, pharetra in nunc sit amet, molestie varius dui. Pellentesque quis eros sed sapien scelerisque vulputate. Donec ut gravida eros. Ut facilisis eleifend placerat. In non ligula leo.
        </br></br>
        Fusce ut quam nec elit fringilla imperdiet. Ut felis ipsum, ultricies ut consequat id, cursus quis lectus. Suspendisse potenti. Nunc nulla felis, faucibus id ullamcorper vel, efficitur sed dui. Integer vitae ligula nec leo tincidunt eleifend. Duis ante nibh, scelerisque vitae risus eget, iaculis pellentesque est. Curabitur ac mi neque. Aenean vulputate lorem nunc, nec tincidunt nulla faucibus a. Nam tempus felis lorem, vitae eleifend ex imperdiet vel. Aenean egestas odio quam, dapibus posuere purus rhoncus vel. Aenean volutpat ultricies nisi, et convallis dui luctus nec. Integer ornare nibh felis, ut condimentum justo pharetra eu. Curabitur commodo pellentesque mi. Nulla vestibulum erat ut magna efficitur lobortis. Etiam bibendum consequat vulputate. Sed pulvinar dapibus odio ut vulputate.
        </br></br>
        Nulla eu tincidunt metus. Sed lobortis sodales egestas. Praesent a tellus vel ligula lobortis fermentum et non mauris. Aenean tempus elementum euismod. In semper imperdiet ex, eget ultricies erat facilisis sed. Integer porta odio non nunc sodales, in ultrices justo vehicula. Pellentesque tempor aliquam arcu in tincidunt. Pellentesque rhoncus ultrices nisi, eleifend aliquet lorem aliquam ac. Curabitur porta semper ipsum id imperdiet. Aenean interdum justo in dui eleifend, ac pretium mi laoreet. Praesent vitae aliquam risus. Sed mollis blandit luctus. Pellentesque ante lacus, accumsan sed volutpat at, aliquet ut mauris.
        </br></br>
        In hac habitasse platea dictumst. Mauris luctus elementum libero, at blandit ex commodo vel. Morbi eleifend massa a neque pellentesque ornare. Pellentesque finibus ut neque vitae interdum. Pellentesque at vehicula quam, non porttitor nulla. Suspendisse maximus malesuada urna eget hendrerit. Proin faucibus lacus a ante cursus dapibus. Nullam lobortis accumsan condimentum. Phasellus mauris elit, dictum vitae commodo quis, condimentum at tellus. Etiam ut pharetra enim. Cras ut sapien a metus vulputate tincidunt. Cras vel vestibulum nunc, in molestie justo.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam volutpat metus magna, at porta nulla scelerisque eget. Vivamus a nisi dolor. Vestibulum ut tellus vitae leo ultrices eleifend ac sit amet orci. Donec condimentum ipsum ut lacinia consequat. Proin quis fringilla ante. Pellentesque id condimentum felis, nec venenatis lectus. Sed aliquet id tellus at rutrum. Phasellus placerat nisi dolor, at laoreet diam vehicula a. Duis libero nunc, semper at metus nec, condimentum efficitur ex. Ut lobortis sagittis tellus ac aliquam. Cras convallis, ligula vel vehicula ullamcorper, orci odio auctor ex, eu accumsan mauris arcu et enim. Etiam placerat diam imperdiet tristique porta. Phasellus porta interdum purus, at maximus erat egestas nec. Nunc tincidunt porttitor mi, sit amet feugiat ligula pretium eget.
        </br></br>
        Pellentesque nec sollicitudin ex, ut fermentum leo. Integer condimentum ac ante nec rutrum. Aenean pulvinar hendrerit enim, porttitor lobortis risus volutpat vitae. Etiam at mi ut nisi pulvinar porta sed interdum velit. Ut lacinia in quam quis mattis. Vestibulum ac arcu hendrerit, porttitor odio quis, tempor nisi. Nam id libero purus. Fusce eu mi eget eros tempor placerat malesuada eu purus. Donec non eros sit amet leo dictum consequat eget vel dui. Donec ac cursus turpis, ut condimentum diam. Vivamus luctus urna purus, ut ultricies ipsum tincidunt ac. Suspendisse sit amet ipsum lorem.
        </br></br>
        Nullam urna lorem, pulvinar at urna eu, luctus laoreet felis. Integer neque nunc, congue vitae sapien et, volutpat condimentum nisi. Phasellus ac augue vitae nisi vestibulum gravida eget molestie lacus. Vivamus magna elit, pharetra in nunc sit amet, molestie varius dui. Pellentesque quis eros sed sapien scelerisque vulputate. Donec ut gravida eros. Ut facilisis eleifend placerat. In non ligula leo.
        </br></br>
        Fusce ut quam nec elit fringilla imperdiet. Ut felis ipsum, ultricies ut consequat id, cursus quis lectus. Suspendisse potenti. Nunc nulla felis, faucibus id ullamcorper vel, efficitur sed dui. Integer vitae ligula nec leo tincidunt eleifend. Duis ante nibh, scelerisque vitae risus eget, iaculis pellentesque est. Curabitur ac mi neque. Aenean vulputate lorem nunc, nec tincidunt nulla faucibus a. Nam tempus felis lorem, vitae eleifend ex imperdiet vel. Aenean egestas odio quam, dapibus posuere purus rhoncus vel. Aenean volutpat ultricies nisi, et convallis dui luctus nec. Integer ornare nibh felis, ut condimentum justo pharetra eu. Curabitur commodo pellentesque mi. Nulla vestibulum erat ut magna efficitur lobortis. Etiam bibendum consequat vulputate. Sed pulvinar dapibus odio ut vulputate.
        </br></br>
        Nulla eu tincidunt metus. Sed lobortis sodales egestas. Praesent a tellus vel ligula lobortis fermentum et non mauris. Aenean tempus elementum euismod. In semper imperdiet ex, eget ultricies erat facilisis sed. Integer porta odio non nunc sodales, in ultrices justo vehicula. Pellentesque tempor aliquam arcu in tincidunt. Pellentesque rhoncus ultrices nisi, eleifend aliquet lorem aliquam ac. Curabitur porta semper ipsum id imperdiet. Aenean interdum justo in dui eleifend, ac pretium mi laoreet. Praesent vitae aliquam risus. Sed mollis blandit luctus. Pellentesque ante lacus, accumsan sed volutpat at, aliquet ut mauris.
        </br></br>
        In hac habitasse platea dictumst. Mauris luctus elementum libero, at blandit ex commodo vel. Morbi eleifend massa a neque pellentesque ornare. Pellentesque finibus ut neque vitae interdum. Pellentesque at vehicula quam, non porttitor nulla. Suspendisse maximus malesuada urna eget hendrerit. Proin faucibus lacus a ante cursus dapibus. Nullam lobortis accumsan condimentum. Phasellus mauris elit, dictum vitae commodo quis, condimentum at tellus. Etiam ut pharetra enim. Cras ut sapien a metus vulputate tincidunt. Cras vel vestibulum nunc, in molestie justo.
    </p>

<?php require '/home/adrian/Documents/dev/billet-simple/src/View/Layout/footer.php'; ?>